### ISSUE TITLE
[ログイン]ログインボタンをタップした際、一度しかストリームが流れない。

### ISSUE THREAD

**Issue by snabezawa-cq** [snabezawa-cq/RxBookManager-iOS#24]

**Comment by ikawashima-cq** [comment]
@snabezawa-cq 
ボタンのタップが初回押下時しか流れていないため、エラーとなって再度押下したいときにできない状態になっています。再押下用のSubjectをViewControllerに作って渡しておげてください。

とりあえずログインできればよきかと思います。

**Comment by snabezawa-cq** [comment]
@ikawashima-cq 
ありがとうございます！調べてみます！

**Comment by ikawashima-cq** [comment]
@snabezawa-cq 

```
.flatMap { [unowned self] (mail, password) -> Observable<Event<UserAccountEntity>> in
                return self.dependency.signIn(email: mail, password: password)
                .materialize()
            }
            .share(replay: 1)
```

ちょっとみてみたのですがmaterializeを上記のようにしてObservable<Event>で流せば解決すると思います。

**Comment by snabezawa-cq** [comment]
@ikawashima-cq 
Observableの型にEventを追加したところ、
無事、ストリームが流れました。🌊
<Event>とここら辺の処理、もう少し復習します！


## before
変更前
<img width="642" alt="スクリーンショット 2019-09-01 17 38 56" src="https://user-images.githubusercontent.com/46508203/64073915-6bced080-ccdf-11e9-8cde-8e2abcb7b01e.png">

変更前2
<img width="740" alt="スクリーンショット 2019-09-01 17 32 04" src="https://user-images.githubusercontent.com/46508203/64073849-8785a700-ccde-11e9-8801-51644503a3bb.png">

## after
<img width="625" alt="スクリーンショット 2019-09-01 17 34 57" src="https://user-images.githubusercontent.com/46508203/64073866-d6334100-ccde-11e9-857e-3479dc139823.png">
